//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dolphin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DolphinActiveX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DolphinActiveX() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dolphin.Resources.DolphinActiveX", typeof(DolphinActiveX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visittkortvisning.
        /// </summary>
        internal static string CardDisplay {
            get {
                return ResourceManager.GetString("CardDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre størrelse.
        /// </summary>
        internal static string ChangeSize {
            get {
                return ResourceManager.GetString("ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukk vindu.
        /// </summary>
        internal static string CloseWindow {
            get {
                return ResourceManager.GetString("CloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakt.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontakter.
        /// </summary>
        internal static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rens.
        /// </summary>
        internal static string DataGridClearButtonText {
            get {
                return ResourceManager.GetString("DataGridClearButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Søk.
        /// </summary>
        internal static string DataGridSearchButtonText {
            get {
                return ResourceManager.GetString("DataGridSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett kontakt.
        /// </summary>
        internal static string DeleteContact {
            get {
                return ResourceManager.GetString("DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett kontakter.
        /// </summary>
        internal static string DeleteContacts {
            get {
                return ResourceManager.GetString("DeleteContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vil du virkelig slette den valgte/aktive raden.
        /// </summary>
        internal static string DoYouReallyWantToDeleteSelectedRow {
            get {
                return ResourceManager.GetString("DoYouReallyWantToDeleteSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vil du skrive ut denne listen.
        /// </summary>
        internal static string DoYouWantToPrintThisList {
            get {
                return ResourceManager.GetString("DoYouWantToPrintThisList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropp en kolonne her for å gruppere.
        /// </summary>
        internal static string DropColumnHereToGroup {
            get {
                return ResourceManager.GetString("DropColumnHereToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre verdi.
        /// </summary>
        internal static string EditValue {
            get {
                return ResourceManager.GetString("EditValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finn kontakt.
        /// </summary>
        internal static string FindContact {
            get {
                return ResourceManager.GetString("FindContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skjul.
        /// </summary>
        internal static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mer informasjon.
        /// </summary>
        internal static string MooreInformation {
            get {
                return ResourceManager.GetString("MooreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flytt ned.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flytt opp.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny kontakt.
        /// </summary>
        internal static string NewContact {
            get {
                return ResourceManager.GetString("NewContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen kontakter.
        /// </summary>
        internal static string NoContacts {
            get {
                return ResourceManager.GetString("NoContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen treff.
        /// </summary>
        internal static string NoHit {
            get {
                return ResourceManager.GetString("NoHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passerte begynnelesen.
        /// </summary>
        internal static string PassedBeginning {
            get {
                return ResourceManager.GetString("PassedBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passerte slutten.
        /// </summary>
        internal static string PassedEnd {
            get {
                return ResourceManager.GetString("PassedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv ut.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spørsmål.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilder.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk etter.
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søking i kolonne.
        /// </summary>
        internal static string SearchingColumn {
            get {
                return ResourceManager.GetString("SearchingColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis som en fane i hovedvindu.
        /// </summary>
        internal static string ShowAsATabInMainWIndow {
            get {
                return ResourceManager.GetString("ShowAsATabInMainWIndow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis som integrert i hovedvindu.
        /// </summary>
        internal static string ShowAsDockedInMainWindow {
            get {
                return ResourceManager.GetString("ShowAsDockedInMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis som eget frittstående vindu.
        /// </summary>
        internal static string ShowAsStandaloneWindow {
            get {
                return ResourceManager.GetString("ShowAsStandaloneWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis filter.
        /// </summary>
        internal static string ShowFilter {
            get {
                return ResourceManager.GetString("ShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv inn en tekst og trykk søk. Bruk * foran teksten for å søke på innhold (og ikke &apos;begynner med&apos;).
        /// </summary>
        internal static string WriteTextAndSearchUseSpecialSign {
            get {
                return ResourceManager.GetString("WriteTextAndSearchUseSpecialSign", resourceCulture);
            }
        }
    }
}
